#!/usr/bin/env python
# SPDX-FileCopyrightText: 2025 Stanford University, ETH Zurich, and the project authors (see CONTRIBUTORS.md)
# SPDX-FileCopyrightText: 2025 This source file is part of the OpenTSLM open-source project.
#
# SPDX-License-Identifier: MIT

"""
Generate Chain-of-Thought (CoT) rationales for CaReSound audio dataset using GPT-4o-mini.

This script:
1. Loads CaReSound dataset from HuggingFace
2. Uses patient-level splits from data/caresound_patient_splits.json
   (generated by scripts/data_prep/create_patient_splits.py) to ensure no data leakage
3. Generates mel-spectrogram visualizations for each audio sample
4. Uses GPT-4o-mini vision API to generate step-by-step reasoning
5. Saves results as CSV files (train/val/test splits)
6. Creates a zip file for easy distribution

Estimated cost: ~$13 for full dataset (32,620 samples) with GPT-4o-mini
Cost per sample: ~$0.0004

Usage:
    # Full dataset
    python scripts/data_prep/generate_audio_cot.py --audio_dir data/caresound/audio

    # Small test (10 samples)
    python scripts/data_prep/generate_audio_cot.py --audio_dir data/caresound/audio --num_samples 10
"""

import os
import sys
import argparse
import json
import base64
import io
import glob
import time
import re
import matplotlib.pyplot as plt
from openai import OpenAI
import pandas as pd
import numpy as np
import zipfile
from tqdm.auto import tqdm
import warnings
from datasets import load_dataset

# Import audio utilities
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))
from opentslm.time_series_datasets.audio_util import load_audio, preprocess_audio

# ---------------------------
# Constants
# ---------------------------
OUTPUT_DIR = "data/caresound_cot"
TRAIN_CSV = os.path.join(OUTPUT_DIR, "caresound_train_cot.csv")
VAL_CSV = os.path.join(OUTPUT_DIR, "caresound_val_cot.csv")
TEST_CSV = os.path.join(OUTPUT_DIR, "caresound_test_cot.csv")
ZIP_FILE = os.path.join(OUTPUT_DIR, "caresound_cot.zip")
SPECTROGRAM_DIR = os.path.join(OUTPUT_DIR, "spectrograms")

client = OpenAI()

# ---------------------------
# Spectrogram generation
# ---------------------------
def generate_spectrogram_image(audio_data, sample_rate=16000, output_path=None):
    """
    Generate mel-spectrogram visualization for GPT-4o-mini to analyze.

    Args:
        audio_data: Audio waveform (numpy array)
        sample_rate: Sample rate in Hz
        output_path: Path to save PNG (if None, saves to temp file)

    Returns:
        Path to saved spectrogram image
    """
    try:
        import librosa
        import librosa.display
    except ImportError:
        raise ImportError("librosa is required. Install with: pip install librosa")

    # Generate mel-spectrogram
    mel_spec = librosa.feature.melspectrogram(
        y=audio_data,
        sr=sample_rate,
        n_mels=128,
        fmax=8000,
        hop_length=512
    )
    mel_spec_db = librosa.power_to_db(mel_spec, ref=np.max)

    # Create figure
    fig, ax = plt.subplots(figsize=(12, 6))
    img = librosa.display.specshow(
        mel_spec_db,
        sr=sample_rate,
        x_axis='time',
        y_axis='mel',
        fmax=8000,
        ax=ax
    )
    fig.colorbar(img, ax=ax, format='%+2.0f dB')
    ax.set_title('Mel-Spectrogram')
    plt.tight_layout()

    # Save
    if output_path is None:
        output_path = "temp_spectrogram.png"

    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close(fig)

    return output_path

# ---------------------------
# CoT Generation Prompts
# ---------------------------

SYSTEM_PROMPT = """\
You are a clinical audio reasoning assistant specialized in cardiac and respiratory auscultation analysis.

Your task is to analyze a mel-spectrogram derived from an auscultation recording and produce a clinically grounded reasoning paragraph.

Your reasoning must be evidence-based and anchored in observable spectro-temporal features.

Do NOT generate generic explanations.
Do NOT systematically negate every possible abnormality.
Do NOT repeat the instruction checklist.

You must ground your reasoning in:
- Specific frequency characteristics (approximate ranges if relevant)
- Temporal structure (inspiratory vs expiratory phases, cardiac cycle timing)
- Intensity envelope and dynamic variation
- Signal morphology (continuous bands, vertical spikes, harmonic streaks, etc.)
- Physiological interpretation (what the signal implies about airflow or pathology)

You must reference at least:
- one temporal feature
- one frequency-related observation
- one morphology-related feature

The reasoning must:
- Be a single coherent paragraph
- Be 120–180 words
- Avoid bullet points or numbered steps
- Avoid meta language (do not say "based on the prompt" or "as instructed")
- Mention the final answer ONLY in the last sentence, formatted as "Answer: <answer>"

Ensure that your reasoning is specific to this case and would not apply verbatim to a different recording."""

# ---------------------------
# CoT Generation with Vision API
# ---------------------------
def generate_audio_cot_rationale(
    spectrogram_path,
    question,
    answer,
    dataset_name,
    patient_id,
    use_mini=True
):
    """
    Use GPT-4o-mini to generate Chain-of-Thought reasoning from spectrogram.

    Args:
        spectrogram_path: Path to spectrogram image
        question: Diagnostic question
        answer: Ground truth answer
        dataset_name: Name of dataset (ICBHI, CirCor, etc.)
        patient_id: Patient ID
        use_mini: Use gpt-4o-mini (cheaper) instead of gpt-4o

    Returns:
        Tuple of (prompt, rationale)
    """
    # Create prompt
    prompt = create_audio_classification_prompt(question, answer, dataset_name)

    # Read and encode image
    with open(spectrogram_path, "rb") as image_file:
        image_data = base64.b64encode(image_file.read()).decode('utf-8')

    # Call GPT-4o-mini vision API
    model = "gpt-4o-mini" if use_mini else "gpt-4o"

    max_retries = 5
    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {
                        "role": "system",
                        "content": SYSTEM_PROMPT,
                    },
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": prompt},
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": f"data:image/png;base64,{image_data}",
                                    "detail": "high"
                                }
                            }
                        ]
                    }
                ],
                temperature=0.7,
                max_tokens=500,
                seed=42
            )

            rationale = response.choices[0].message.content.strip()

            # Extract token usage
            usage = {
                "prompt_tokens": getattr(response.usage, "prompt_tokens", 0),
                "completion_tokens": getattr(response.usage, "completion_tokens", 0),
                "total_tokens": getattr(response.usage, "total_tokens", 0),
            }

            # Ensure it ends with "Answer: {answer}"
            if not rationale.endswith(f"Answer: {answer}"):
                # Try to find where answer was mentioned
                if f"Answer: {answer}" in rationale:
                    # Already has it somewhere, just ensure it's at the end
                    parts = rationale.split(f"Answer: {answer}")
                    rationale = parts[0].strip() + f" Answer: {answer}"
                else:
                    # Add it
                    rationale = rationale.strip() + f" Answer: {answer}"

            return prompt, rationale, usage

        except Exception as e:
            error_str = str(e)
            if "429" in error_str or "rate_limit" in error_str.lower():
                # Parse wait time from error message (e.g. "Please try again in 321ms")
                wait = 1.0  # default fallback
                match = re.search(r"try again in (\d+)(ms|s)", error_str)
                if match:
                    val = int(match.group(1))
                    unit = match.group(2)
                    wait = val / 1000.0 if unit == "ms" else float(val)
                wait = max(wait, 0.5) * (1.5 ** attempt)  # exponential backoff
                if attempt < max_retries - 1:
                    time.sleep(wait)
                    continue
            # Non-retryable error or exhausted retries
            print(f"Error calling OpenAI API for patient {patient_id}: {e}")
            return prompt, f"Unable to generate rationale. Answer: {answer}", {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}

    # Should not reach here, but just in case
    return prompt, f"Unable to generate rationale. Answer: {answer}", {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}

def create_audio_classification_prompt(question, correct_answer, dataset_name):
    """
    Create user-side prompt for audio CoT generation.

    Designed to elicit clinically grounded, spectrogram-anchored reasoning
    that connects signal → physiology → diagnosis.

    Args:
        question: Diagnostic question
        correct_answer: Ground truth answer
        dataset_name: Dataset name (e.g. SPRSound, ICBHI, CirCor)

    Returns:
        Prompt string
    """
    prompt = f"""You are analyzing a mel-spectrogram from a {dataset_name} auscultation recording.

Question: {question}

The correct answer is: {correct_answer}

Provide a clinically grounded reasoning paragraph based on the spectrogram characteristics that leads to the answer "{correct_answer}".
End with "Answer: {correct_answer}"

Answer:"""
    return prompt

# ---------------------------
# Audio file discovery
# ---------------------------

# ── ICBHI: lung auscultation location codes ──
# Filenames: {patient}_{session}p{channel}_{location}_{mode}_{device}.wav
_ICBHI_LOCATION_MAP = {
    "Tc": ["tracheal", "trachea"],
    "Al": ["anterior left"],
    "Ar": ["anterior right"],
    "Pl": ["posterior left"],
    "Pr": ["posterior right"],
    "Ll": ["lateral left"],
    "Lr": ["lateral right"],
}
_ICBHI_KEYWORD_TO_CODE = {}
for _code, _keywords in _ICBHI_LOCATION_MAP.items():
    for _kw in _keywords:
        _ICBHI_KEYWORD_TO_CODE[_kw] = _code

# ── CirCor: cardiac valve location codes ──
# Filenames: {patient}_{valve}.wav  (AV, MV, PV, TV)
_CIRCOR_LOCATION_MAP = {
    "AV": ["aortic valve", "aortic"],
    "MV": ["mitral valve", "mitral"],
    "PV": ["pulmonic valve", "pulmonic", "pulmonary valve", "pulmonary"],
    "TV": ["tricuspid valve", "tricuspid"],
}
_CIRCOR_KEYWORD_TO_CODE = {}
for _code, _keywords in _CIRCOR_LOCATION_MAP.items():
    for _kw in _keywords:
        _CIRCOR_KEYWORD_TO_CODE[_kw] = _code


def _extract_location_from_question(question, dataset_name):
    """
    Extract body/valve location from a question string.

    Returns a location code suitable for filename matching:
      - ICBHI:  'Tc', 'Pl', 'Ar', ... (matched via _{code}_ in filename)
      - CirCor: 'AV', 'MV', 'PV', 'TV' (matched via _{code}. in filename)
      - Others: None
    """
    q_lower = question.lower()

    if dataset_name == "ICBHI":
        for keyword, code in _ICBHI_KEYWORD_TO_CODE.items():
            if keyword in q_lower:
                return code

    elif dataset_name == "CirCor":
        for keyword, code in _CIRCOR_KEYWORD_TO_CODE.items():
            if keyword in q_lower:
                return code

    # SPRSound: questions don't reference specific positions (p1-p4)
    # ZCHSound / KAUH: single file per patient
    return None


def _find_audio_files(patient_id, dataset_name, audio_dir):
    """
    Find audio file(s) for a patient, searching flat dir, subdirs, and suffixed names.
    
    Supports:
      - Flat exact:      audio_dir/{patient_id}.wav
      - Flat suffixed:   audio_dir/{patient_id}_*.wav  (e.g. _p1, _AV, _MV)
      - Subdir exact:    audio_dir/{dataset}/{patient_id}.wav
      - Subdir suffixed: audio_dir/{dataset}/{patient_id}_*.wav
    """
    extensions = [".wav", ".flac", ".mp3", ".ogg"]
    found = []
    for ext in extensions:
        # Flat exact
        exact = os.path.join(audio_dir, f"{patient_id}{ext}")
        if os.path.exists(exact):
            found.append(exact)
        # Flat suffixed
        for p in glob.glob(os.path.join(audio_dir, f"{patient_id}_*{ext}")):
            if p not in found:
                found.append(p)
        # Subdir exact
        sub_exact = os.path.join(audio_dir, dataset_name, f"{patient_id}{ext}")
        if os.path.exists(sub_exact) and sub_exact not in found:
            found.append(sub_exact)
        # Subdir suffixed
        for p in glob.glob(os.path.join(audio_dir, dataset_name, f"{patient_id}_*{ext}")):
            if p not in found:
                found.append(p)
    return sorted(found)


def _select_audio_for_question(audio_paths, question, dataset_name):
    """
    Select the best audio file for a given question.

    Location-aware matching:
      - ICBHI:  "wheezes at tracheal?" → file with _Tc_ in name
      - CirCor: "murmur at aortic valve?" → file with _AV in name
      - Others: first file (no location info in questions)

    Args:
        audio_paths: List of audio file paths for this patient
        question: The diagnostic question text
        dataset_name: Dataset name (e.g. 'ICBHI', 'CirCor', 'SPRSound')

    Returns:
        (selected_path, location_code_or_None)
    """
    if not audio_paths:
        return None, None

    loc_code = _extract_location_from_question(question, dataset_name)
    if loc_code is None:
        # General question or dataset without location matching
        return audio_paths[0], None

    # Search for the matching file
    for path in audio_paths:
        basename = os.path.basename(path)
        if dataset_name == "ICBHI":
            # ICBHI: location is mid-filename, e.g. 130_1p2_Tc_mc_AKGC417L.wav
            if f"_{loc_code}_" in basename:
                return path, loc_code
        elif dataset_name == "CirCor":
            # CirCor: valve is suffix, e.g. 50214_AV.wav
            name_no_ext = os.path.splitext(basename)[0]
            if name_no_ext.endswith(f"_{loc_code}"):
                return path, loc_code

    # No matching file found — fall back to first
    return audio_paths[0], None


# ---------------------------
# Main processing logic
# ---------------------------
DEFAULT_PATIENT_SPLITS_PATH = "data/caresound_patient_splits.json"


def load_caresound_dataset(cache_dir=None, patient_splits_path=DEFAULT_PATIENT_SPLITS_PATH):
    """Load CaReSound dataset from HuggingFace, split by patient-level mapping.

    If ``patient_splits_path`` exists, the HuggingFace rows are pooled and
    re-assigned to ``train`` / ``val`` / ``test`` according to the patient
    mapping (no patient overlap between splits).

    Falls back to the legacy HF train/test split when no mapping file exists.

    Returns:
        dict[str, list[dict]]  —  ``{"train": [...], "val": [...], "test": [...]}``
    """
    print("Loading CaReSound dataset from HuggingFace...")
    hf_dataset = load_dataset("tsnngw/CaReSound", cache_dir=cache_dir)
    print(f"  HF train: {len(hf_dataset['train'])} rows")
    print(f"  HF test:  {len(hf_dataset['test'])} rows")

    use_patient_split = (
        patient_splits_path is not None
        and os.path.exists(patient_splits_path)
    )

    if use_patient_split:
        with open(patient_splits_path) as f:
            split_map = json.load(f)["splits"]  # patient_id → "train"/"val"/"test"
        print(f"  Patient-level split loaded ({len(split_map)} patients)")

        # Pool ALL HF rows and redistribute
        splits = {"train": [], "val": [], "test": []}
        unmapped = 0
        for hf_split_name in ("train", "test"):
            for row in hf_dataset[hf_split_name]:
                pid = str(row["patient_id"])
                assigned = split_map.get(pid)
                if assigned in splits:
                    splits[assigned].append(dict(row))
                else:
                    unmapped += 1

        for s_name in ("train", "val", "test"):
            print(f"  {s_name}: {len(splits[s_name])} QA pairs (patient-disjoint)")
        if unmapped:
            print(f"  ⚠ {unmapped} rows with unmapped patient_id (skipped)")
        return splits
    else:
        print("  ⚠ No patient split file found — using legacy HF train/test (val = test copy)")
        return {
            "train": [dict(row) for row in hf_dataset["train"]],
            "val":   [dict(row) for row in hf_dataset["test"]],
            "test":  [dict(row) for row in hf_dataset["test"]],
        }

def process_audio_sample(
    sample,
    audio_dir,
    spectrogram_dir,
    use_mini=True,
    save_spectrograms=False
):
    """
    Process a single audio sample to generate CoT rationale.

    Args:
        sample: Dataset sample with patient_id, question, answer, dataset
        audio_dir: Directory containing audio files
        spectrogram_dir: Directory to save spectrograms
        use_mini: Use GPT-4o-mini (cheaper)
        save_spectrograms: Save spectrograms to disk (for debugging)

    Returns:
        Dictionary with processed data or None if failed
    """
    patient_id = sample["patient_id"]
    question = sample["question"]
    answer = sample["answer"]
    dataset_name = sample.get("dataset", "Medical")

    # Find audio file(s) — supports flat dir, subdirs, and suffixed names
    audio_paths = _find_audio_files(patient_id, dataset_name, audio_dir)

    if not audio_paths:
        return None

    # Select the best audio file for this specific question
    # (e.g., tracheal recording for "wheezes at tracheal location?" questions)
    audio_path, loc_code = _select_audio_for_question(audio_paths, question, dataset_name)

    try:
        # Spectrogram name matches the audio filename (minus extension)
        # e.g. 130_1p2_Tc_mc_AKGC417L.wav → 130_1p2_Tc_mc_AKGC417L.png
        audio_basename = os.path.splitext(os.path.basename(audio_path))[0]
        spec_name = f"{audio_basename}.png"
        spectrogram_path = os.path.join(spectrogram_dir, spec_name)
        os.makedirs(spectrogram_dir, exist_ok=True)
        if not os.path.exists(spectrogram_path):
            # Load audio and preprocess to 1D mono
            waveform, sr = load_audio(audio_path, target_sample_rate=16000)
            waveform = preprocess_audio(waveform, sample_rate=sr, target_sample_rate=16000)
            audio_data = waveform.numpy()
            generate_spectrogram_image(audio_data, sample_rate=16000, output_path=spectrogram_path)

        # Generate CoT rationale
        prompt, rationale, usage = generate_audio_cot_rationale(
            spectrogram_path=spectrogram_path,
            question=question,
            answer=answer,
            dataset_name=dataset_name,
            patient_id=patient_id,
            use_mini=use_mini
        )

        # Clean up spectrogram if not saving
        if not save_spectrograms:
            try:
                os.remove(spectrogram_path)
            except FileNotFoundError:
                pass

        return {
            "patient_id": patient_id,
            "dataset": dataset_name,
            "question": question,
            "answer": answer,
            "rationale": rationale,
            "prompt": prompt,
            "audio_file": os.path.basename(audio_path),
            "_usage": usage,  # token usage for cost tracking
        }

    except Exception as e:
        print(f"Error processing patient {patient_id}: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Generate CoT rationales for CaReSound audio dataset")
    parser.add_argument(
        "--audio_dir",
        type=str,
        default="./data/caresound_audio/audio_merged",
        help="Directory containing audio files"
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=OUTPUT_DIR,
        help="Directory to save output files"
    )
    parser.add_argument(
        "--num_samples",
        type=int,
        default=None,
        help="Number of samples to process (None = all). Use small number for testing."
    )
    parser.add_argument(
        "--use_gpt4o",
        action="store_true",
        help="Use GPT-4o instead of GPT-4o-mini (more expensive but potentially better quality)"
    )
    parser.add_argument(
        "--save_spectrograms",
        action="store_true",
        help="Save spectrograms to disk (useful for debugging)"
    )
    parser.add_argument(
        "--cache_dir",
        type=str,
        default=None,
        help="Cache directory for HuggingFace datasets"
    )
    parser.add_argument(
        "--checkpoint_every",
        type=int,
        default=100,
        help="Save checkpoint every N samples"
    )

    args = parser.parse_args()

    # Create output directories
    os.makedirs(args.output_dir, exist_ok=True)
    spectrogram_dir = os.path.join(args.output_dir, "spectrograms")
    os.makedirs(spectrogram_dir, exist_ok=True)

    # Check if audio directory exists
    if not os.path.exists(args.audio_dir):
        print(f"Error: Audio directory not found: {args.audio_dir}")
        print("Please download audio files first.")
        sys.exit(1)

    # Load dataset (patient-split aware)
    dataset = load_caresound_dataset(
        cache_dir=args.cache_dir,
        patient_splits_path=DEFAULT_PATIENT_SPLITS_PATH,
    )

    # Determine model
    model_name = "GPT-4o" if args.use_gpt4o else "GPT-4o-mini"
    print(f"\n{'='*60}")
    print(f"Using {model_name} for CoT generation")
    print(f"{'='*60}\n")

    # --- Token / cost tracking ---
    total_prompt_tokens = 0
    total_completion_tokens = 0
    total_tokens = 0
    use_mini = not args.use_gpt4o

    # Pricing per 1M tokens (as of 2025)
    if use_mini:
        price_input_per_1m = 0.150    # GPT-4o-mini input
        price_output_per_1m = 0.600   # GPT-4o-mini output
        model_label = "GPT-4o-mini"
    else:
        price_input_per_1m = 2.50     # GPT-4o input
        price_output_per_1m = 10.00   # GPT-4o output
        model_label = "GPT-4o"

    def _save_checkpoint(results, checkpoint_file, label=""):
        """Save checkpoint to CSV (safe: write to temp then rename)."""
        if not results:
            return
        tmp = checkpoint_file + ".tmp"
        df = pd.DataFrame(results)
        df.to_csv(tmp, index=False)
        os.replace(tmp, checkpoint_file)  # atomic on same filesystem
        if label:
            print(f"\n  💾 Checkpoint saved: {len(results)} samples processed ({label})")

    # Map split name → output CSV path
    _SPLIT_CSV = {"train": TRAIN_CSV, "val": VAL_CSV, "test": TEST_CSV}

    # Process each split (now patient-disjoint: train / val / test)
    for split in ["train", "val", "test"]:
        print(f"\n{'='*60}")
        print(f"Processing {split} split")
        print(f"{'='*60}\n")

        split_data = dataset[split]  # list[dict]

        # Limit samples if specified
        num_samples = args.num_samples if args.num_samples else len(split_data)
        num_samples = min(num_samples, len(split_data))

        # --- Pre-scan: report audio coverage ---
        missing_audio = 0
        for i in range(num_samples):
            s = split_data[i]
            pid = str(s["patient_id"])
            ds = s.get("dataset", "")
            if not _find_audio_files(pid, ds, args.audio_dir):
                missing_audio += 1
        valid_audio = num_samples - missing_audio
        skip_pct = 100.0 * missing_audio / num_samples if num_samples else 0
        print(f"📊 Audio coverage: {valid_audio}/{num_samples} valid samples "
              f"({missing_audio} missing, {skip_pct:.2f}% will be skipped)")
        print(f"Processing {num_samples} samples...")

        results = []
        skipped = 0
        failed = 0
        new_since_checkpoint = 0
        checkpoint_file = os.path.join(args.output_dir, f"checkpoint_{split}.csv")

        # Load existing checkpoint if exists
        # Key: (patient_id, question) to handle multiple questions per patient
        processed_keys = set()
        if os.path.exists(checkpoint_file):
            print(f"Loading checkpoint from {checkpoint_file}...")
            checkpoint_df = pd.read_csv(checkpoint_file)
            # Filter out any failed rationales from previous runs
            valid_mask = ~checkpoint_df['rationale'].str.startswith("Unable to generate", na=False)
            checkpoint_df = checkpoint_df[valid_mask]
            results = checkpoint_df.to_dict('records')
            for r in results:
                processed_keys.add((str(r['patient_id']), str(r['question'])))
            print(f"Resuming from {len(results)} already processed samples")

        # Process samples with graceful shutdown on interrupt
        try:
            for idx in tqdm(range(num_samples), desc=f"Generating CoT for {split}"):
                sample = split_data[idx]

                # Skip if already processed (keyed on patient_id + question)
                key = (str(sample["patient_id"]), str(sample["question"]))
                if key in processed_keys:
                    continue

                result = process_audio_sample(
                    sample=sample,
                    audio_dir=args.audio_dir,
                    spectrogram_dir=spectrogram_dir,
                    use_mini=use_mini,
                    save_spectrograms=args.save_spectrograms
                )

                if result is not None:
                    # Check if rationale actually succeeded (not a fallback)
                    rationale = result.get("rationale", "")
                    if rationale.startswith("Unable to generate"):
                        failed += 1
                        continue  # Don't save failed rationales

                    # Accumulate token usage
                    usage = result.pop("_usage", {})
                    total_prompt_tokens += usage.get("prompt_tokens", 0)
                    total_completion_tokens += usage.get("completion_tokens", 0)
                    total_tokens += usage.get("total_tokens", 0)

                    results.append(result)
                    processed_keys.add(key)
                    new_since_checkpoint += 1
                else:
                    skipped += 1

                # Checkpoint every N *new* samples
                if new_since_checkpoint >= args.checkpoint_every:
                    _save_checkpoint(results, checkpoint_file, f"{split}")
                    new_since_checkpoint = 0

        except KeyboardInterrupt:
            print(f"\n\n⚠️  Interrupted! Saving progress...")
            _save_checkpoint(results, checkpoint_file, f"{split} - interrupted")
            print(f"   Saved {len(results)} results. Re-run to resume.")
            sys.exit(0)
        except Exception as e:
            print(f"\n\n❌ Unexpected error: {e}")
            _save_checkpoint(results, checkpoint_file, f"{split} - error")
            print(f"   Saved {len(results)} results. Re-run to resume.")
            raise

        # Final save for this split
        _save_checkpoint(results, checkpoint_file, f"{split} - complete")

        # Save final results
        if results:
            df = pd.DataFrame(results)
            output_file = _SPLIT_CSV[split]
            df.to_csv(output_file, index=False)
            print(f"\n✅  Saved {len(results)} samples to {output_file}")
            if skipped > 0:
                print(f"   ⚠  Skipped {skipped} samples (missing audio, "
                      f"{100.0 * skipped / num_samples:.2f}%)")
            if failed > 0:
                print(f"   ⚠  Failed {failed} API calls (not saved, will retry on re-run)")
        else:
            print(f"\n⚠️  No samples processed for {split} split")

    # Create zip file
    print(f"\n{'='*60}")
    print("Creating zip file...")
    print(f"{'='*60}\n")

    with zipfile.ZipFile(ZIP_FILE, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for csv_file in [TRAIN_CSV, VAL_CSV, TEST_CSV]:
            if os.path.exists(csv_file):
                zipf.write(csv_file, os.path.basename(csv_file))
                print(f"  Added {os.path.basename(csv_file)} to zip")

    # ── Cost summary ──
    input_cost = total_prompt_tokens / 1_000_000 * price_input_per_1m
    output_cost = total_completion_tokens / 1_000_000 * price_output_per_1m
    total_cost = input_cost + output_cost

    print(f"\n{'='*60}")
    print(f"💰 API USAGE & COST SUMMARY  ({model_label})")
    print(f"{'='*60}")
    print(f"  Prompt tokens:      {total_prompt_tokens:>12,}")
    print(f"  Completion tokens:  {total_completion_tokens:>12,}")
    print(f"  Total tokens:       {total_tokens:>12,}")
    print(f"  ─────────────────────────────────")
    print(f"  Input cost:         ${input_cost:>11.4f}")
    print(f"  Output cost:        ${output_cost:>11.4f}")
    print(f"  ✅ Total cost:       ${total_cost:>11.4f}")

    print(f"\n{'='*60}")
    print("✅  Generation Complete!")
    print(f"{'='*60}")
    print(f"\nOutput files (patient-disjoint splits):")
    print(f"  Training CSV:   {TRAIN_CSV}")
    print(f"  Validation CSV: {VAL_CSV}")
    print(f"  Test CSV:       {TEST_CSV}")
    print(f"  Zip file:       {ZIP_FILE}")
    print(f"\nNext steps:")
    print(f"  1. Review generated rationales in CSV files")
    print(f"  2. Upload {ZIP_FILE} to Polybox or cloud storage")
    print(f"  3. Update CareSoundCoTDataset loader with download URL")

if __name__ == "__main__":
    main()
